# Generated by Django 5.2.7 on 2025-10-18 16:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("academics", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Faculties",
            fields=[
                ("faculty_id", models.AutoField(primary_key=True, serialize=False)),
                ("first_name", models.TextField()),
                ("last_name", models.TextField()),
                ("email", models.TextField()),
                ("phone_number", models.TextField()),
                ("designation", models.TextField()),
                ("date_of_joining", models.DateField()),
                ("address", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("modified_by", models.TextField()),
                ("is_active", models.BooleanField(default=True)),
                (
                    "department",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="faculties",
                        to="academics.batches",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Students",
            fields=[
                ("student_id", models.AutoField(primary_key=True, serialize=False)),
                ("first_name", models.TextField()),
                ("last_name", models.TextField()),
                ("email", models.TextField()),
                ("phone_number", models.TextField()),
                ("date_of_birth", models.DateField()),
                ("address", models.TextField()),
                ("father_name", models.TextField()),
                ("father_phno", models.TextField()),
                ("parents_gaurdian_mail", models.TextField()),
                ("mother_name", models.TextField()),
                ("mother_phno", models.TextField()),
                ("guardian_name", models.TextField()),
                ("gaurdian_phno", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("modified_by", models.TextField()),
                ("is_active", models.BooleanField(default=True)),
                (
                    "batch",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="students",
                        to="academics.batches",
                    ),
                ),
                (
                    "branch",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="students",
                        to="academics.branches",
                    ),
                ),
            ],
        ),
    ]
