# Generated by Django 5.2.7 on 2025-10-19 04:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0003_remove_classes_students_classes_students"),
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="students",
            name="gaurdian_phno",
        ),
        migrations.AddField(
            model_name="students",
            name="guardian_phno",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="faculties",
            name="department",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="faculties",
                to="academics.branches",
            ),
        ),
        migrations.AlterField(
            model_name="faculties",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name="faculties",
            name="phone_number",
            field=models.CharField(unique=True),
        ),
        migrations.AlterField(
            model_name="students",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name="students",
            name="guardian_name",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="students",
            name="phone_number",
            field=models.CharField(unique=True),
        ),
    ]
