# Generated by Django 5.2.7 on 2025-10-23 15:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("academics", "0001_initial"),
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Attendance",
            fields=[
                ("attendance_id", models.AutoField(primary_key=True, serialize=False)),
                ("date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Present", "Present"),
                            ("Absent", "Absent"),
                            ("Leave", "Leave"),
                        ],
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("modified_by", models.TextField()),
                ("is_active", models.BooleanField(default=True)),
                (
                    "class_sub",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendance_records",
                        to="academics.class_sub",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendance_records",
                        to="accounts.student",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Backlogs",
            fields=[
                ("backlog_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "exam_type",
                    models.CharField(
                        choices=[
                            ("Internal", "Internal"),
                            ("External", "External"),
                            ("Final", "Final"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("Pending", "Pending"), ("Cleared", "Cleared")],
                        max_length=10,
                    ),
                ),
                ("attempt_number", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("modified_by", models.TextField()),
                ("is_active", models.BooleanField(default=True)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="backlogs",
                        to="accounts.student",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="backlogs",
                        to="academics.subjects",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Fees",
            fields=[
                ("fee_id", models.AutoField(primary_key=True, serialize=False)),
                ("amount_due", models.DecimalField(decimal_places=2, max_digits=10)),
                ("amount_paid", models.DecimalField(decimal_places=2, max_digits=10)),
                ("due_date", models.DateField()),
                ("payment_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Paid", "Paid"),
                            ("Pending", "Pending"),
                            ("Overdue", "Overdue"),
                        ],
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("modified_by", models.TextField()),
                ("is_active", models.BooleanField(default=True)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fees",
                        to="accounts.student",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Marks",
            fields=[
                ("mark_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "exam_type",
                    models.CharField(
                        choices=[
                            ("Internal", "Internal"),
                            ("External", "External"),
                            ("Final", "Final"),
                        ],
                        max_length=20,
                    ),
                ),
                ("score", models.IntegerField()),
                ("grade", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("modified_by", models.TextField()),
                ("is_active", models.BooleanField(default=True)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="marks",
                        to="accounts.student",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="marks",
                        to="academics.subjects",
                    ),
                ),
            ],
        ),
    ]
