# Generated by Django 5.2.7 on 2025-11-01 13:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0002_initial"),
        ("accounts", "0001_initial"),
        ("records", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="attendance",
            options={
                "ordering": ["-date"],
                "verbose_name": "Attendance Record",
                "verbose_name_plural": "Attendance Records",
            },
        ),
        migrations.AlterField(
            model_name="attendance",
            name="modified_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="modified_attendance",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="attendance",
            unique_together={("student", "date", "class_sub")},
        ),
    ]
