# Generated by Django 5.2.7 on 2025-10-19 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("records", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fees",
            name="payment_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
