# Generated by Django 5.2.7 on 2025-10-19 04:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        (
            "accounts",
            "0002_remove_students_gaurdian_phno_students_guardian_phno_and_more",
        ),
        ("records", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ParentAlerts",
            fields=[
                ("alert_id", models.AutoField(primary_key=True, serialize=False)),
                ("message", models.TextField()),
                ("timestamp", models.DateTimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[("Sent", "Sent"), ("Read", "Read")], max_length=10
                    ),
                ),
                ("created_at", models.DateTimeField()),
                ("modified_at", models.DateTimeField()),
                ("modified_by", models.TextField()),
                ("is_active", models.BooleanField(default=True)),
                (
                    "attendance",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="alerts",
                        to="records.attendance",
                    ),
                ),
                (
                    "backlog",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="alerts",
                        to="records.backlogs",
                    ),
                ),
                (
                    "fee",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="alerts",
                        to="records.fees",
                    ),
                ),
                (
                    "mark",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="alerts",
                        to="records.marks",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alerts",
                        to="accounts.students",
                    ),
                ),
            ],
        ),
    ]
