# Generated by Django 5.2.7 on 2025-11-01 11:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("communications", "0001_initial"),
        ("records", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="parentalerts",
            name="attendance",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="alerts",
                to="records.attendance",
            ),
        ),
        migrations.AddField(
            model_name="parentalerts",
            name="mark",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="alerts",
                to="records.mark",
            ),
        ),
        migrations.AddField(
            model_name="parentalerts",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="alerts",
                to="accounts.student",
            ),
        ),
    ]
