# Generated by Django 5.2.7 on 2025-10-23 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Batches",
            fields=[
                ("batch_id", models.AutoField(primary_key=True, serialize=False)),
                ("batch_name", models.TextField()),
                ("start_year", models.IntegerField()),
                ("end_year", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("modified_by", models.TextField()),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="Branches",
            fields=[
                ("branch_id", models.AutoField(primary_key=True, serialize=False)),
                ("branch_name", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("modified_by", models.TextField()),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="Class_sub",
            fields=[
                ("class_sub_id", models.AutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("modified_by", models.TextField()),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="Classes",
            fields=[
                ("class_id", models.AutoField(primary_key=True, serialize=False)),
                ("class_name", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("modified_by", models.TextField()),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="Subjects",
            fields=[
                ("subject_id", models.AutoField(primary_key=True, serialize=False)),
                ("subject_name", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("modified_by", models.TextField()),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
    ]
