# Generated by Django 5.2.6 on 2025-11-08 20:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("academics", "0001_initial"),
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="class_sub",
            name="faculty",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="subject_classes",
                to="accounts.faculty",
            ),
        ),
        migrations.AddField(
            model_name="classes",
            name="batch",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="classes",
                to="academics.batches",
            ),
        ),
        migrations.AddField(
            model_name="classes",
            name="class_teacher",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="teaching_classes",
                to="accounts.faculty",
            ),
        ),
        migrations.AddField(
            model_name="classes",
            name="students",
            field=models.ManyToManyField(
                blank=True, related_name="enrolled_classes", to="accounts.student"
            ),
        ),
        migrations.AddField(
            model_name="class_sub",
            name="class_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subjects",
                to="academics.classes",
            ),
        ),
        migrations.AddField(
            model_name="subjects",
            name="branch",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subjects",
                to="academics.branches",
            ),
        ),
        migrations.AddField(
            model_name="class_sub",
            name="subject",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="class_subjects",
                to="academics.subjects",
            ),
        ),
    ]
