# Generated by Django 5.2.7 on 2025-10-18 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0002_initial"),
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="classes",
            name="students",
        ),
        migrations.AddField(
            model_name="classes",
            name="students",
            field=models.ManyToManyField(
                blank=True, related_name="enrolled_classes", to="accounts.students"
            ),
        ),
    ]
