# Generated by Django 5.2.7 on 2025-10-19 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0003_remove_classes_students_classes_students"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="branches",
            name="HOD",
        ),
    ]
