# Generated by Django 5.2.7 on 2025-10-21 18:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0005_branches_hod"),
        (
            "accounts",
            "0002_remove_students_gaurdian_phno_students_guardian_phno_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="branches",
            name="HOD",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="headed_branches",
                to="accounts.faculties",
            ),
        ),
    ]
